### ISSUE TITLE
WARC parser should be protocol agnostic 

### ISSUE THREAD

**Issue by amallia** [pisa-engine/warcpp#2]
When we parse a WARC file, we split the content into two parts: header and content.
In my opinion, this should be (eventually) done by an HTTP/HTML parser. 

As a consequence, `warcpp` should never fail if anything in the HTTP content is wrong, either the HTTP header or the HTTP content.  

I propose to change a bit the design of this library in order to remove any reference to HTTP. Any library users, such as `pisa`, should have additional HTTP/HTML functions/classes in order to strip out or parse HTTP header (depending what they want to achieve or need) .

**Comment by elshize** [comment]
Agreed.

**Comment by amallia** [comment]
We will do:
```
1. parse header, and skip one CRLF
2. read `content-length` bytes to `content`
3. skip two CRLF
4. done
```
